INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(1, '0', '00', '', '', '', 0, 0, 1, 0, 0, 'ATIVANDO MONITOR', 0);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(2, '0', '02', '', '', '', 1, 1, 1, 0, 0, 'MTA ARMADO REMOTO', 0);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(3, '0', '04', '', '', '', 1, 0, 0, 0, 1, 'FALHA EM ATIVAR REMOTO', 0);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(4, '0', '0F', '', '', '', 0, 0, 1, 0, 0, 'AZ-DTRADLD: ATIVANDO ALARME', 0);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(5, '0', '10', '', '', 'ALR', 1, 0, 0, 0, 1, 'MONITOR ATIVO COM SETOR 11 BLOQUEADO AUTOMÁTICO', 0);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(6, '0', '20', '', '', '', 0, 0, 0, 0, 0, 'EVITA ATIVACAO AUTOMATICA', 0);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(7, '0', '40', '', '', '', 1, 0, 4, 0, 1, 'PROCEDIMENTO DE PARTIDA MTA / DTRADM / MCO', 0);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(8, '0', '41', '', '', '', 1, 1, 0, 0, 0, 'MTA: RECONFIGURACAO (ON)', 0);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(9, '0', '80', '', '', '', 0, 0, 2, 0, 0, 'DESATIVANDO MONITOR', 0);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(10, '0', '82', '', '', '', 0, 1, 2, 0, 0, 'MTA DESATIVADO REMOTO', 0);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(11, '0', '8F', '', '', '', 0, 0, 2, 0, 0, 'AZ-DTRADLD: DESATIVANDO ALARME', 0);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(12, '1', '00', '', '', 'EME', 1, 0, 0, 0, 1, 'ALERTA MEDICO', 0);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(13, '1', '0F', '', '', 'EME', 1, 0, 0, 0, 1, 'ALERTA MEDICO', 0);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(14, '1', '60', '', '', 'ALR', 1, 0, 0, 0, 1, 'CTD: CANAL RF ABERTO', 0);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(15, '1', '70', '', '', 'ALR', 1, 0, 0, 0, 1, 'LINHA TELEFONICA CORTADA', 0);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(16, '1', '7F', '', '', 'ALR', 1, 0, 0, 0, 1, 'LINHA TELEFONICA CORTADA', 0);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(17, '2', '00', '', '00', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(18, '2', '01', '', '01', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(19, '2', '02', '', '02', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(20, '2', '03', '', '03', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(21, '2', '04', '', '04', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(22, '2', '05', '', '05', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(23, '2', '06', '', '06', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(24, '2', '07', '', '07', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(25, '2', '08', '', '08', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(26, '2', '09', '', '09', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(27, '2', '0A', '', '0A', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(28, '2', '0B', '', '0B', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(29, '2', '0C', '', '0C', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(30, '2', '0D', '', '0D', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(31, '2', '0E', '', '0E', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(32, '2', '0F', '', '0F', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(33, '2', '10', '', '10', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(34, '2', '11', '', '11', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(35, '2', '12', '', '12', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(36, '2', '13', '', '13', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(37, '2', '14', '', '14', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(38, '2', '15', '', '15', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(39, '2', '16', '', '16', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(40, '2', '17', '', '17', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(41, '2', '18', '', '18', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(42, '2', '19', '', '19', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(43, '2', '1A', '', '1A', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(44, '2', '1B', '', '1B', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(45, '2', '1C', '', '1C', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(46, '2', '1D', '', '1D', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(47, '2', '1E', '', '1E', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(48, '2', '1F', '', '1F', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(49, '2', '20', '', '20', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(50, '2', '21', '', '21', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(51, '2', '22', '', '22', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(52, '2', '23', '', '23', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(53, '2', '24', '', '24', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(54, '2', '25', '', '25', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(55, '2', '26', '', '26', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(56, '2', '27', '', '27', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(57, '2', '28', '', '28', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(58, '2', '29', '', '29', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(59, '2', '2A', '', '2A', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(60, '2', '2B', '', '2B', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(61, '2', '2C', '', '2C', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(62, '2', '2D', '', '2D', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(63, '2', '2E', '', '2E', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(64, '2', '2F', '', '2F', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(65, '2', '30', '', '30', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(66, '2', '31', '', '31', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(67, '2', '32', '', '32', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(68, '2', '33', '', '33', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(69, '2', '34', '', '34', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(70, '2', '35', '', '35', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(71, '2', '36', '', '36', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(72, '2', '37', '', '37', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(73, '2', '38', '', '38', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(74, '2', '39', '', '39', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(75, '2', '3A', '', '3A', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(76, '2', '3B', '', '3B', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(77, '2', '3C', '', '3C', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(78, '2', '3D', '', '3D', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(79, '2', '3E', '', '3E', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(80, '2', '3F', '', '3F', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(81, '2', '40', '', '40', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(82, '2', '41', '', '41', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(83, '2', '42', '', '42', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(84, '2', '43', '', '43', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(85, '2', '44', '', '44', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(86, '2', '45', '', '45', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(87, '2', '46', '', '46', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(88, '2', '47', '', '47', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(89, '2', '48', '', '48', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(90, '2', '49', '', '49', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(91, '2', '4A', '', '4A', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(92, '2', '4B', '', '4B', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(93, '2', '4C', '', '4C', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(94, '2', '4D', '', '4D', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(95, '2', '4E', '', '4E', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(96, '2', '4F', '', '4F', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(97, '2', '50', '', '50', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(98, '2', '51', '', '51', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(99, '2', '52', '', '52', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(100, '2', '53', '', '53', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(101, '2', '54', '', '54', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(102, '2', '55', '', '55', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(103, '2', '56', '', '56', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(104, '2', '57', '', '57', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(105, '2', '58', '', '58', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(106, '2', '59', '', '59', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(107, '2', '5A', '', '5A', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(108, '2', '5B', '', '5B', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(109, '2', '5C', '', '5C', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(110, '2', '5D', '', '5D', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(111, '2', '5E', '', '5E', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(112, '2', '5F', '', '5F', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(113, '2', '60', '', '60', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(114, '2', '61', '', '61', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(115, '2', '62', '', '62', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(116, '2', '63', '', '63', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(117, '2', '64', '', '64', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(118, '2', '65', '', '65', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(119, '2', '66', '', '66', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(120, '2', '67', '', '67', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(121, '2', '68', '', '68', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(122, '2', '69', '', '69', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(123, '2', '6A', '', '6A', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(124, '2', '6B', '', '6B', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(125, '2', '6C', '', '6C', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(126, '2', '6D', '', '6D', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(127, '2', '6E', '', '6E', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(128, '2', '6F', '', '6F', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(129, '2', '70', '', '70', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(130, '2', '71', '', '71', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(131, '2', '72', '', '72', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(132, '2', '73', '', '73', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(133, '2', '74', '', '74', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(134, '2', '75', '', '75', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(135, '2', '76', '', '76', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(136, '2', '77', '', '77', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(137, '2', '78', '', '78', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(138, '2', '79', '', '79', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(139, '2', '7A', '', '7A', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(140, '2', '7B', '', '7B', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(141, '2', '7C', '', '7C', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(142, '2', '7D', '', '7D', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(143, '2', '7E', '', '7E', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(144, '2', '7F', '', '7F', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(145, '2', '80', '', '80', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(146, '2', '81', '', '81', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(147, '2', '82', '', '82', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(148, '2', '83', '', '83', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(149, '2', '84', '', '84', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(150, '2', '85', '', '85', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(151, '2', '86', '', '86', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(152, '2', '87', '', '87', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(153, '2', '88', '', '88', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(154, '2', '89', '', '89', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(155, '2', '8A', '', '8A', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(156, '2', '8B', '', '8B', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(157, '2', '8C', '', '8C', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(158, '2', '8D', '', '8D', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(159, '2', '8E', '', '8E', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(160, '2', '8F', '', '8F', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(161, '2', '90', '', '90', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(162, '2', '91', '', '91', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(163, '2', '92', '', '92', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(164, '2', '93', '', '93', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(165, '2', '94', '', '94', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(166, '2', '95', '', '95', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(167, '2', '96', '', '96', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(168, '2', '97', '', '97', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(169, '2', '98', '', '98', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(170, '2', '99', '', '99', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(171, '2', '9A', '', '9A', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(172, '2', '9B', '', '9B', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(173, '2', '9C', '', '9C', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(174, '2', '9D', '', '9D', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(175, '2', '9E', '', '9E', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(176, '2', '9F', '', '9F', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(177, '2', 'A0', '', 'A0', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(178, '2', 'A1', '', 'A1', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(179, '2', 'A2', '', 'A2', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(180, '2', 'A3', '', 'A3', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(181, '2', 'A4', '', 'A4', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(182, '2', 'A5', '', 'A5', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(183, '2', 'A6', '', 'A6', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(184, '2', 'A7', '', 'A7', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(185, '2', 'A8', '', 'A8', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(186, '2', 'A9', '', 'A9', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(187, '2', 'AA', '', 'AA', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(188, '2', 'AB', '', 'AB', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(189, '2', 'AC', '', 'AC', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(190, '2', 'AD', '', 'AD', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(191, '2', 'AE', '', 'AE', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(192, '2', 'AF', '', 'AF', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(193, '2', 'B0', '', 'B0', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(194, '2', 'B1', '', 'B1', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(195, '2', 'B2', '', 'B2', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(196, '2', 'B3', '', 'B3', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(197, '2', 'B4', '', 'B4', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(198, '2', 'B5', '', 'B5', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(199, '2', 'B6', '', 'B6', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
INSERT INTO ESTATUS_TBL
(ID, STATUS, REFERENCIA1, REFERENCIA2, SETOR, GRUPO, ALARME, MENSAGEM, MONITOR, IDENTIFICACAO, OCORRENCIA, DESCRICAO, COR)
VALUES(200, '2', 'B7', '', 'B7', 'ALR', 1, 0, 0, 0, 2, 'INVASAO SETOR', 255);
