server:
  error:
    include-stacktrace: never
  servlet:
    context-path: /api
spring:
  data:
    mongodb:
      uri: mongodb://fukhpt_azsimdb:*TVgcp!Og&wzeAox@mongodb-ag-br1-2.conteige.cloud:27017/fukhpt_azsimdb

logging:
  level:
    ROOT: INFO